name: Actions Workflow
on: 
  pull_request:
    types: [closed, opened, assigned, reopened]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          ls
          pwd
      - name: Checkout
        uses: actions/checkout@v2
      - name: List Files After
        run: |
          pwd
          ls -a
      - name: Simple Javascript Action
        uses: actions/hello-world-javascript-action@v1.1
        id: greet
        with:
          who-to-greet: 'Mona the Octocat'
      - name: Log Greeting Time
        run: echo ${{steps.greet.outputs.time}}