name: Container
on: 
  push:
jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: node:14-alpine3.14
    steps:
      - name: Log Node Version
        run: |
          node -v
          cat /etc/os-release