name: Matrix 
on: push
jobs:
  node-version:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [6,8, 10]
    steps:
      - name: Log Node Version
        run: node -v
      - uses: actions/setup-node@v2
        with:
          node-version: 6
      - name: Log Node Version
        run: node -v
